services:
  postgres:
    build:
      context: ./src/postgres
      dockerfile: Dockerfile
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - ${COMPOSE_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${COMPOSE_PORT}
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 4000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/books_db
    restart: always
